name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  WertsfyAPI-Workflow-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
       