name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]

jobs:
  Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "WertsfyAPI Workflow Actions"
      
      - name: Fazendo Checkout
        uses: actions/checkout@v2
      
