name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]

jobs:
  wty-workflow-base:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo Checkout
        uses: actions/checkout@v2
      
