name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]

jobs:
  Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "WertsfyAPI Workflow Actions"
      
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: 'eslint made the following change'
