name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  wty-workflow-base:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo Checkout
        uses: actions/checkout@v2
      
      - name: Criando Hashes
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: hashes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes.txt
