name: "@workflow-main"

on:
  push:
    branches: [ v1.0 ]
  pull_request:
    branches: [ v1.0 ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "WertsfyAPI Workflow Actions"
      