name: "@WertsfyAPI-Workflow/auto-dependabot-pull-request-merge"

on: pull_request
jobs:
  auto-merge:
    - name: Merge
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        intervalSeconds: 10
        timeoutSeconds: 30