name: "@WertsfyAPI-Workflow/Generics"

on: [push]
jobs:
  Generics:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Setup
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - uses: auto-it/setup-auto@v1
      - name: Release
        run: auto shipit 
      
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
