name: "@WertsfyAPI-Workflow/Dependabot"

# Trigger the workflow on pull request
on: 
  pull_request_target:
    branches: [ v1.0 ]
  push:
    branches: [ v1.0 ]

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: cognitedata/auto-approve-dependabot-action@v3.0.1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}