name: "@WertsfyAPI-Workflow/Autochangelog"

on: [push, workflow_dispatch]
jobs:
  AutoChangelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Changelog generator
      uses: dittrichlucas/changelog-generator@main
      with:
        token: ${{ github.token }}
        repo: ${{ github.repository }}

    - name: Check changelog file
      run: cat CHANGELOG.md