name: wertsfy-workflow

jobs:
  release:
    runs-on: v1.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: auto-it/setup-auto@v1

      - name: Release
        run: auto shipit

on: pull_request
  jobs:
    auto-merge:
      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30