name: "@WertsfyAPI-Workflow/Lab-lockfile-testing"

on: [ push ]
jobs:
  testing:
    name: Testing Lockfile NodeJS
    runs-on: ubuntu-latest
    steps:
      # J Lockfile Testing
      - name: Check out a copy of the repo
        uses: actions/checkout@v2
      - uses: mansona/npm-lockfile-version@v1